# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
@EXPLICIT
https://conda.anaconda.org/esri/win-64/arcgispro-2.4-0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/blas-1.0-mkl.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/ca-certificates-2019.11.28-hecc5488_0.tar.bz2
https://conda.anaconda.org/esri/win-64/icc_rt-2019.0.4-arcgispro_0.tar.bz2
https://conda.anaconda.org/esri/win-64/intel-openmp-2019.4-arcgispro_245.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/msys2-conda-epoch-20160418-1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pandoc-2.7.3-0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/vs2015_runtime-14.16.27012-hf0eaf9b_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/winpty-0.4.3-4.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gmp-6.1.0-2.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-libwinpthread-git-5.0.0.4634.697f757-2.tar.bz2
https://conda.anaconda.org/esri/win-64/mkl-2019.3-arcgispro_203.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/vc-14.1-h0510ff6_4.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libblas-3.8.0-8_mkl.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libsodium-1.0.17-h2fa13f4_0.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-libs-core-5.3.0-7.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/openssl-1.1.1d-hfa6e2cd_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/sqlite-3.30.1-hfa6e2cd_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/zlib-1.2.11-h2fa13f4_1006.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libcblas-3.8.0-8_mkl.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/liblapack-3.8.0-8_mkl.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libpng-1.6.37-h7602738_0.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-libgfortran-5.3.0-6.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/python-3.6.8-h9f7ef89_7.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/zeromq-4.3.2-h6538335_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/alabaster-0.7.12-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/asn1crypto-1.2.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/atomicwrites-1.3.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/attrs-19.3.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backcall-0.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/certifi-2019.11.28-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/chardet-3.0.4-py36_1003.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/colorama-0.4.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/decorator-4.4.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/defusedxml-0.6.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/docutils-0.15.2-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/entrypoints-0.3-py36_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/et_xmlfile-1.0.1-py_1001.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/fastcache-1.1.0-py36hfa6e2cd_0.tar.bz2
https://conda.anaconda.org/esri/win-64/freetype-2.9.1-vc14_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/future-0.17.1-py36_1000.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/idna-2.8-py36_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/imagesize-1.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ipython_genutils-0.2.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jdcal-1.4.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/json5-0.8.5-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/kiwisolver-1.1.0-py36he980bc4_0.tar.bz2
https://repo.anaconda.com/pkgs/msys2/win-64/m2w64-gcc-libs-5.3.0-7.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/markupsafe-1.1.1-py36hfa6e2cd_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/mistune-0.8.4-py36hfa6e2cd_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/more-itertools-8.0.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/mpmath-1.1.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/numpy-base-1.16.2-py36hc3f5095_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pandocfilters-1.4.2-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/parso-0.5.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pickleshare-0.7.5-py36_1000.tar.bz2
https://conda.anaconda.org/esri/win-64/prometheus_client-0.6.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/py-1.8.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pycparser-2.19-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyparsing-2.4.5-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pypdf2-1.26.0-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyshp-1.2.12-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pytz-2019.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pywin32-224-py36hfa6e2cd_1000.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pywin32-ctypes-0.2.0-py36_1000.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pyzmq-18.1.1-py36h16f9016_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/send2trash-1.5.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/simplegeneric-0.8.1-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/six-1.13.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/snowballstemmer-1.9.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sphinx_rtd_theme-0.4.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sphinxcontrib-applehelp-1.0.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sphinxcontrib-devhelp-1.0.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sphinxcontrib-htmlhelp-1.0.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sphinxcontrib-jsmath-1.0.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sphinxcontrib-qthelp-1.0.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sphinxcontrib-serializinghtml-1.1.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/testpath-0.4.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/tornado-6.0.3-py36hfa6e2cd_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wcwidth-0.1.7-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/webencodings-0.5.1-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/win_inet_pton-1.1.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/wincertstore-0.2-py36_1003.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/winkerberos-0.7.0-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/xlrd-1.2.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/xlwt-1.3.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/babel-2.7.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/cffi-1.13.2-py36hb32ad35_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cycler-0.10.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/html5lib-1.0.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/jedi-0.15.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/keyring-19.2.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/openpyxl-3.0.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/packaging-19.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pyrsistent-0.15.6-py36hfa6e2cd_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pysocks-1.7.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/python-dateutil-2.8.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pywinpty-0.5.5-py36_1000.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/setuptools-42.0.2-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/traitlets-4.3.3-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/zipp-0.6.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/bleach-3.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/cryptography-2.8-py36hb32ad35_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/importlib_metadata-0.23-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jinja2-2.10.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/jupyter_core-4.6.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/nose-1.3.7-py36_1002.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pygments-2.5.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/sympy-1.4-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/terminado-0.8.2-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/wheel-0.33.6-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/x86cpu-0.4-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/jsonschema-3.2.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/jupyter_client-5.3.3-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pip-19.3.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pluggy-0.12.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/prompt_toolkit-2.0.9-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pyopenssl-19.1.0-py36_0.tar.bz2
https://conda.anaconda.org/esri/win-64/despatch-0.1.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/ipython-7.8.0-py36h5ca1d4c_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nbformat-4.4.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pytest-5.1.2-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/urllib3-1.25.7-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/ipykernel-5.1.2-py36h5ca1d4c_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/nbconvert-5.6.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/requests-2.22.0-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyter_console-6.0.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/notebook-6.0.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sphinx-2.2.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyterlab_server-1.0.6-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nbsphinx-0.5.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/widgetsnbextension-3.5.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ipywidgets-7.5.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyterlab-1.1.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/cftime-1.0.0b1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/mkl_fft-1.0.13-py36hfa6e2cd_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/mkl_random-1.0.4-py36h830ac7b_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/numpy-1.16.2-py36h19fb1c0_0.tar.bz2
https://conda.anaconda.org/esri/win-64/gdal-2.3.3-arcgispro_1.tar.bz2
https://conda.anaconda.org/esri/win-64/h5py-2.9.0-py36_arcgispro_0.tar.bz2
https://conda.anaconda.org/esri/win-64/matplotlib-3.0.3-py36_0e.tar.bz2
https://conda.anaconda.org/esri/win-64/netcdf4-1.5.0.1-py36_arcgispro_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/numexpr-2.6.9-py36h6538335_1000.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pandas-0.25.1-py36he350917_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/scipy-1.2.1-py36h29ff71c_0.tar.bz2
https://conda.anaconda.org/esri/win-64/arcgis-1.6.2-py36h4f45381_633.tar.bz2
